from diffusers import StableDiffusionPipeline
import torch
import matplotlib.pyplot as plt

pipe=StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

prompt=input("Enter the prompt to generate the image : ")

with torch.autocast("cuda"):
  image=pipe(prompt).images[0]

plt.imshow(image)
plt.axis("off")
plt.title("Generated by Stable Diffusion")
plt.show()
image.save("result/generated_image.png")